In [1]:
import numpy as np
import pandas as pd
import gmplot as gp

In [5]:
df = pd.read_csv('data_stephen_fix_header.csv', header=[0])

In [6]:
# merge materials (target) classes
# types of ice -> ice
# types of till -> till

# df['materials'].replace(['ICE'], 'ice', regex=True, inplace=True)
df['materials'].replace(['ICE'], 'Ice', regex=True, inplace=True)
df['materials'].replace(['ice'], 'Ice', regex=True, inplace=True)
df['materials'].replace(['Pure Ice'], 'Ice', regex=True, inplace=True)

df['materials'].replace(['Coarse till'], 'Till', regex=True, inplace=True)
df['materials'].replace(['till'], 'Till', regex=True, inplace=True)
df['materials'].replace(['Fine till'], 'Till', regex=True, inplace=True)
df['materials'].replace(['Fine Till'], 'Till', regex=True, inplace=True)

df['materials'].replace(['Till'], 'Sand', regex=True, inplace=True)
df['materials'].replace(['Silt'], 'Sand', regex=True, inplace=True)

df['materials'].replace(['Cobbles'], 'Gravel', regex=True, inplace=True)

df.materials = df.materials.astype('category').cat.codes
# print(df.materials.value_counts().index)



# convert timecodes to year and month columns
datetimes = pd.to_datetime(df['time'])
df['month'] = datetimes.dt.month
df['year'] = datetimes.dt.year

In [7]:
df.head()

,latitude,longitude,time,borehole,depth,frozen,cryostructures,visible_ice,ASTM_2488,materials,organic_cover,top_of_interval,bottom_of_interval,month,year
0,69.16162,-133.08682,2012-03-21T00:00:00Z,0170-1-10,0.15,0,NaN,NaN,TOPSOIL,3,0.3,0.0,0.3,3,2012
1,69.16162,-133.08682,2012-03-21T00:00:00Z,0170-1-10,0.85,1,NaN,Pure ice,ICE,2,0.3,0.3,1.4,3,2012
2,69.16162,-133.08682,2012-03-21T00:00:00Z,0170-1-10,1.90,1,Nf,No visible ice,SW-SM,5,0.3,1.4,2.4,3,2012
3,69.16162,-133.08682,2012-03-21T00:00:00Z,0170-1-10,5.40,1,Nf,No visible ice,GW-GM,5,0.3,2.4,8.4,3,2012
4,69.16105,-133.08880,2012-03-21T00:00:00Z,0170-1-12,1.20,1,Nf,No visible ice,GP-GM,5,0.0,0.0,2.4,3,2012

In [10]:
df2 = df.drop_duplicates(subset='borehole')
df2.head()

mean_lat = df2.latitude.unique().mean()
mean_lng = df2.longitude.unique().mean()

,latitude,longitude,time,borehole,depth,frozen,cryostructures,visible_ice,ASTM_2488,materials,organic_cover,top_of_interval,bottom_of_interval,month,year
0,69.16162,-133.08682,2012-03-21T00:00:00Z,0170-1-10,0.15,0,NaN,NaN,TOPSOIL,3,0.3,0.0,0.3,3,2012
4,69.16105,-133.08880,2012-03-21T00:00:00Z,0170-1-12,1.20,1,Nf,No visible ice,GP-GM,5,0.0,0.0,2.4,3,2012
7,69.15849,-133.08865,2012-03-20T00:00:00Z,0170-1-17,0.30,0,NaN,NaN,ML,5,0.0,0.0,0.6,3,2012
11,69.15908,-133.08968,2012-03-20T00:00:00Z,0170-1-18,0.05,0,NaN,NaN,ORGANICS,3,0.1,0.0,0.1,3,2012
17,69.15886,-133.09090,2012-03-21T00:00:00Z,0170-1-19,1.20,1,Nf,No visible ice,GP,1,0.0,0.0,2.4,3,2012

In [19]:
gmap = gp.GoogleMapPlotter(mean_lat, mean_lng, 8, apikey = "AIzaSyDfyyRArCO9O6fajy0cjZJgOQJqiO7_nNQ")
gmap.heatmap(df2.latitude.tolist(), df2.longitude.tolist())  
# Pass the absolute path
gmap.draw( "map1.html" )